# Backend API Configuration
API_URL = "http://localhost:8000"

# Optional: Direct API Keys (if not using backend)
# OPENAI_API_KEY = "your_openai_api_key_here"
# QLOO_API_KEY = "your_qloo_api_key_here"